# NYT
url_nyt_0 = ('Home Page', 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml')
url_nyt_1 = ('World', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml')
url_nyt_2 = ('U.S.', 'https://rss.nytimes.com/services/xml/rss/nyt/US.xml')
url_nyt_3 = ('Education', 'https://rss.nytimes.com/services/xml/rss/nyt/Education.xml')
url_nyt_4 = ('Politics', 'https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml')
url_nyt_5 = ('NY Region', 'https://rss.nytimes.com/services/xml/rss/nyt/NYRegion.xml')
url_nyt_6 = ('Business', 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml')
url_nyt_7 = ('Economy', 'https://rss.nytimes.com/services/xml/rss/nyt/Economy.xml')
url_nyt_8 = ('Media and Advertising', 'https://rss.nytimes.com/services/xml/rss/nyt/MediaandAdvertising.xml')
url_nyt_9 = ('Technology', 'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml')

# BBC
url_bbc_0 = ('Home Page','https://feeds.bbci.co.uk/news/rss.xml')
url_bbc_1 = ('World', 'https://feeds.bbci.co.uk/news/world/rss.xml')
url_bbc_2 = ('UK', 'https://feeds.bbci.co.uk/news/uk/rss.xml')
url_bbc_3 = ('Business', 'https://feeds.bbci.co.uk/news/business/rss.xml')
url_bbc_4 = ('Politics', 'https://feeds.bbci.co.uk/news/politics/rss.xml')
url_bbc_5 = ('Health', 'https://feeds.bbci.co.uk/news/health/rss.xml')
url_bbc_6 = ('Education', 'https://feeds.bbci.co.uk/news/education/rss.xml')
url_bbc_7 = ('Science and Environment', 'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml')
url_bbc_8 = ('Technology', 'https://feeds.bbci.co.uk/news/technology/rss.xml')
url_bbc_9 = ('Entertainment and Arts', 'https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml') 

# CNN
url_cnn_0 = ('Top Stories', 'http://rss.cnn.com/rss/cnn_topstories.rss')
url_cnn_1 = ('World', 'http://rss.cnn.com/rss/cnn_world.rss')
url_cnn_2 = ('U.S.', 'http://rss.cnn.com/rss/money_latest.rss')
url_cnn_3 = ('Business', 'http://rss.cnn.com/rss/cnn_us.rss')
url_cnn_4 = ('Politics', 'http://rss.cnn.com/rss/cnn_allpolitics.rss')
url_cnn_5 = ('Technology', 'http://rss.cnn.com/rss/cnn_tech.rss')
url_cnn_6 = ('Health', 'http://rss.cnn.com/rss/cnn_health.rss')
url_cnn_7 = ('Entertainment', 'http://rss.cnn.com/rss/cnn_showbiz.rss')
url_cnn_8 = ('Travel', 'http://rss.cnn.com/rss/cnn_travel.rss')
url_cnn_9 = ('CNN Underscored', 'http://rss.cnn.com/cnn-underscored.rss')